 language: CSharp
 sudo: required
 mono:
   - latest 
 install:
   - apt-get install -y --no-install-recommends dotnet-dev-1.0.0-rc2-002416   
   - dotnet --info
   - dotnet restore 
 script: 
   - dotnet test Test/project.json -parallel none