 dist: trusty
 language: CSharp
 sudo: required
 mono:
   - latest 
 install:
   - sudo apt-get install -y --no-install-recommends dotnet-dev-1.0.0-rc2-002416   
   - dotnet --info
   - dotnet restore 
 script:
   - dotnet build Redouble.AspNet.Webpack/project.json 
   - dotnet test Test/project.json -parallel none
   - dotnet build Calculator/project.json