 language: CSharp
 sudo: required
 mono:
   - latest 
 install:
   - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh 
   - dnvm install 1.0.0-rc1-update1 -r mono
   - dnvm list
   - dnu restore 
 script: 
   - dnx -p Test/project.json test -parallel none